# Generated by Django 5.1.5 on 2025-01-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_form_alter_contact_options_alter_index_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
