# Generated by Django 5.1.5 on 2025-01-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_form_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
    ]
